### ISSUE TITLE
Prepare a document describing the concept of the project

### ISSUE THREAD

**Issue by jan-golda** [jan-golda/PW-TensorGraphicalProgramming#1]
> Your task is to develop an informal preliminary functional analysis of the proposed application. Please describe per page / two / three how you imagine the program will work and include a sketch of the user interface.
> 
> Please also provide information about the selected compiler/development environment or additional libraries.
>
> The documents you post should be sent in pdf format

- [x] General description
- [x] Functional requirements (from #3) 
- [x] Non-functional requirements (from #2)
- [x] Concept of the UI (from #4)
- [x] Technologies, libraries and tools

**Comment by jan-golda** [comment]
[jan_golda_concept.pdf](https://github.com/jan-golda/PW-TensorGraphicalProgramming/files/6018201/jan_golda_concept.pdf)
